### ISSUE TITLE
Cannot scroll search results

### ISSUE THREAD

**Issue by Minority103** [riverscuomo/public-bug-hunt#14]
When I search a song in the searching bar, if there are more version, it doesn't let me scroll, it goes up automatically, that makes the songs at the bottom unclickable. 

1. Go to 'Search'
2. Click on 'Search query' 
3. Write a song title with more version eg. 'Pacific' 
4. Scroll down 
5. See error

https://github.com/riverscuomo/public-bug-hunt/assets/144348857/4395a6a6-92de-4511-a6cd-a00027a1b418

**Expected behavior**
Scrolling down witout it going back up. 

 - iOS 16.6
 - Device: iPhone 14 Pro

**Comment by SlightlyCompletely** [comment]
Also occurs on iPad Air 5th gen running iPadOS 16.6.1, but did *not* occur on same iPad when running iPadOS 16.6.0.

**Comment by KCreek1** [comment]
On small screen web app 1.9.0 (173):  the search results appear but cannot be scrolled through so results are limited to only what you can see on the first page. 

In iOS app iPhone:  the results can be scrolled through. It's just the last result is obscured by control bar and can't be clicked on. 

iPhone SE (2nd gen)
iPad (5th gen)
iOS 17.0

**Comment by KCreek1** [comment]
Can now scroll search results on small screen web app on iPhone.

iPhone SE (2nd gen)
iOS 17.0
Web app 1.9.0 (173)

**Comment by KCreek1** [comment]
Can scroll on search results on iPad but not via touch screen. I can only scroll using the scroll shell on a Bluetooth mouse. Seems maybe it's acting more like a desktop version than mobile version in that respect. 

iPad 7th gen
iOS 16.7
Safari browser
Web app 1.9.0 (173)

**Comment by KCreek1** [comment]
Fixed on iOS app 1.9.0 (174). Search results can be scrolled through and last track accessed.

**Comment by SlightlyCompletely** [comment]
Still occurs in Weezify app 1.9.0 174 on iPad Air running iPadOS 17.0.1.

**Comment by SlightlyCompletely** [comment]
> Also occurs on iPad Air 5th gen running iPadOS 16.6.1 in that lower songs cannot be selected/scrolled down to; scroll in this case does not even work at all. Issue did _not_ occur on same iPad when running iPadOS 16.6.0.

Still an issue in Weezify 1.9.0 (174) on iPad Air running iPadOS 17.0.1, though it’s possible to scroll with two fingers to see the bottom of the results before the list bounces back up to make lower tracks unselectable again.

**Comment by KCreek1** [comment]
I noticed that scrolling on ipad or ipad web seems to work fine in that section (like for playlists) unless there is a box on top (search box, app bar).  In that case the scrolling seems to be an issue.  Possibly how the boxes are layered?

**Comment by KCreek1** [comment]
This issue along with issue #47 and part of issue #7 involves touch vs mouse for iPad and iPad web. Scrolling works with mouse but not touch.

**Comment by KCreek1** [comment]
I just tried this on Chromebook browser with touch screen. Same results. 

Maybe for this action touch is not listed as a pointer device kind?

**Comment by SlightlyCompletely** [comment]
> I just tried this on Chromebook browser with touch screen. Same results. 
> 
> Maybe for this action on large screen - touch is not listed as a pointer device kind?
> 
> https://stackoverflow.com/q/69253697

@KCreek1 If you search for playlists, do you find that you can scroll fine on Chromebook, as on iPad? 

Somehow the different search categories (song vs playlist) return results that differ in how they handle scrolling.

**Comment by KCreek1** [comment]
Yes. On search - songs cannot be scrolled. But playlists and artists can be.

**Comment by riverscuomo** [comment]
on the Home screen, did you try scrolling up with your finger on the 'Good MOrning'?

**Comment by riverscuomo** [comment]
So you can't scroll songs from search results? but you can scroll songs in a playlist?

**Comment by SlightlyCompletely** [comment]
@Rivers here’s a video showing how the scrolling works on iPad.

The process shown:

First I’m trying to scroll from roughly the middle of the screen, and the list just keeps bouncing to the top again so I can’t reach anything on the bottom.

Next I try scrolling from the Good Morning area, and I can scroll to the bottom but not to the top again- again the bouncing when my finger is lifted.

Then I head to search and try a similar method (scrolling from middle then scrolling from top area) in song results, getting the same bouncing and inaccessible results as the home screen.

Lastly I search by Playlist and you can see that it’s scrolling completely normally, as the the song title search and home page ought to do.


https://github.com/riverscuomo/public-bug-hunt/assets/144279871/0da60b48-c139-44e3-bcb3-92e7081143ea

**Comment by riverscuomo** [comment]
Does the home screen scroll work on the tablet web app in your browser now? 
Or did it always?

**Comment by KCreek1** [comment]
> Does the home screen scroll work on the tablet web app in your browser now? 
> 
> Or did it always?

Yes. On tablet web app the home screen now scrolls by touch. It didn't do that before.

**Comment by KCreek1** [comment]
I realize there is another issue mentioned here but this also has to do with scrolling. 

Currently on large screen web (tablet) - if I do a search I have a couple different scenarios once I enter a search:

-The songs do not scroll correctly initially. (This is unchanged.)

Scenario A: 
1. Enter search and see initial song results
2. Select "artist"
3. Choose an artist profile (does not matter which, I tried several)
4. Return to search results
5. Tap on "songs"
6. Song list is now the BTP playlist and CAN be scrolled.

Scenario B:
1. Enter search and see initial song results
2. Select "playlist" 
3. Choose a playlist
4. Return to search results
5. Tap on "songs"
6. Song list is now whatever playlist I selected under the other tab. If it is a best of playlist - I CAN scroll. If it is a user created playlist - I CANNOT scroll.

So the scrolling issue on "songs" seems that it may be related to whether it is a best of playlist or not?

**Comment by KCreek1** [comment]
I found that you can scroll up on the list if you swipe above the songs, playlists, artists tabs. You have to do it above the yellow line (see pic). I don't know what that indicates - maybe another box is blocking it? I still can't scroll down. 

![image](https://github.com/riverscuomo/public-bug-hunt/assets/144278926/afe1a775-8192-42d1-a16a-b376a8c370b6)

https://github.com/riverscuomo/public-bug-hunt/assets/144278926/235633e9-8ca6-4d84-b92e-dbd217d5af81

**Comment by KCreek1** [comment]
The search results for songs once again cannot be scrolled on small web on iPhone. It doesn't roll and retract - the list doesn't move at all.


iPhone SE (2nd gen)
iOS 17.0.3
Safari browser
Web app 1.10.0 (177)

**Comment by KCreek1** [comment]
This is once again resolved on iPhone both in iOS app and small web 1.10.0 (179). 

But remains on iPad both in app and on web. Wherein you can scroll up as long as it's above the yellow line. 



> I found that you can scroll up on the list in iPad if you swipe above the songs, playlists, artists tabs. You have to do it above the yellow line (see pic). I don't know what that indicates - maybe another box is blocking it? I still can't scroll down. 
> 
> ![image](https://github.com/riverscuomo/public-bug-hunt/assets/144278926/afe1a775-8192-42d1-a16a-b376a8c370b6)
> 
> https://github.com/riverscuomo/public-bug-hunt/assets/144278926/235633e9-8ca6-4d84-b92e-dbd217d5af81

**Comment by SlightlyCompletely** [comment]
All scrolling issues resolved on iPad with upgrade to Weezify 186.

Device: iPad Air 5th gen
OS: iPadOS 17.0.3
Weezify 1.12.0 (186)
