### ISSUE TITLE
Most recent bundle purchased appears twice on profile

### ISSUE THREAD

**Issue by SlightlyCompletely** [riverscuomo/public-bug-hunt#21]
After purchasing a bundle in the market, that bundle will appear twice on the profile page. The duplicate does disappear after some undetermined period of time or when purchasing another bundle—then the newer bundle is one that is duplicated in the profile.

1. Go to Market and purchase a bundle.
2. After receiving a message that the bundle was added to the library, navigate from Market to Profile.
3. Profile will display the most recently purchased bundle twice.

**Expected behavior**
Bundles should only be displayed once in profile.

 - Device: iPad Air 5th gen
 - OS: iPadOS 16.6.1
 - Weezify v1.8.6
 

Issue also occurs on iPhone 7 running iOS 15.7.8.
![IMG_2274](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/cce0547e-8f16-45db-ae35-0c679efa2c8b)

**Comment by KCreek1** [comment]
Recreated on iPhone SE (2nd gen) running iOS 16.6.1 and Weezify app 1.8.6 (153). Second bundle icon disappeared once logged out and back in.

**Comment by slobulike** [comment]
Same behaviour on Android 1.8.9

**Comment by KCreek1** [comment]
I think this is fixed. I did not see it in iOS 1.9.0 (171).

**Comment by SlightlyCompletely** [comment]
Still occurs on iPhone 7 (running iOS 15.7.9) in 1.9.0 (171).

![IMG_8261](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/bcee6ab6-6efc-472e-ae7b-b4795b9aaa8a)

**Comment by SlightlyCompletely** [comment]
Also still occurs on iPad Air 5th gen (running iPadOS 16.6.1) in Weezify 1.9.0 (171).

![IMG_2420](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/382608a8-26be-4a57-9a8e-faea44d425fb)

**Comment by SlightlyCompletely** [comment]
Remains an issue in v1.9.2 (176) in iPadOS 17.0.1.

**Comment by SlightlyCompletely** [comment]
Resolved for iPad with Weezify 1.10.0 (179).

**Comment by SlightlyCompletely** [comment]
@slobulike Is this resolved for you? If so, I believe we can close this issue.

**Comment by slobulike** [comment]
I've just tried with a couple of different accounts and newly purchased
bundles only appeared once using Android so think we're good to close.

**Comment by Mel01000001** [comment]
Android 184 (1.11.0), purchased bundle initially appears twice, but is rectified after closing and reopening app.
![Screenshot_20231028_212604](https://github.com/riverscuomo/public-bug-hunt/assets/144282154/1bf0ab3b-c6cb-4a29-9ff1-dc6980cf1e0f)

**Comment by riverscuomo** [comment]
database record looks correct:

![image](https://github.com/riverscuomo/public-bug-hunt/assets/24362267/d85638cf-0a21-434d-9fd9-deee87b21146)

**Comment by urbainn** [comment]
![image](https://github.com/riverscuomo/public-bug-hunt/assets/47057465/50c74c2f-0ff1-4956-ae39-4935eefcc4bd)
Happens again on Android 1.12.0 (186), though it also goes back to normal once I close and re-open the app.

**Comment by SlightlyCompletely** [comment]
Issue occurs again in Weezify 1.12.0 (186) on iPad Air 5th gen running iPadOS 17.0.3.

**Comment by KCreek1** [comment]
I have not seen a double playlist in the last 2 builds on iPhone.
